# Generated by Django 4.2.1 on 2023-07-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dossier', models.CharField(max_length=50, null=True)),
                ('parent_dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_parent', to='ged.dossier')),
            ],
            options={
                'verbose_name': ' Dossier',
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=355, null=True)),
                ('nom_fichier', models.CharField(max_length=200, null=True)),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.dossier')),
            ],
            options={
                'verbose_name': ' Fichier',
                'db_table': 'fichier',
            },
        ),
    ]
