# Generated by Django 4.2.1 on 2023-09-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Devise',
                'db_table': 'devise',
            },
        ),
        migrations.CreateModel(
            name='EtatDossier',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Etat Dossier',
                'db_table': 'etat_dossier',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Exercice',
                'db_table': 'exercice',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('cd_organisation', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=80)),
                ('siege', models.CharField(max_length=80)),
                ('date_adhesion', models.DateTimeField()),
                ('document_adhesion', models.CharField(max_length=100)),
                ('rib', models.CharField(max_length=100)),
                ('Devise_2', models.CharField(max_length=100)),
                ('Devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.devise')),
            ],
            options={
                'verbose_name': ' Organisation',
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Periode',
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='PlanEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.periode')),
            ],
            options={
                'verbose_name': ' Plan Engagement',
                'db_table': 'plan_engagement',
            },
        ),
        migrations.CreateModel(
            name='SourceFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=70)),
                ('libelle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Source Financement',
                'db_table': 'source_financement',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Statut',
                'db_table': 'statut',
            },
        ),
        migrations.CreateModel(
            name='TypeTutelle',
            fields=[
                ('cd_type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Type Tutelle',
                'db_table': 'type_tutelle',
            },
        ),
        migrations.CreateModel(
            name='Tutelle',
            fields=[
                ('cd_tutelle', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=70)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.typetutelle')),
            ],
            options={
                'verbose_name': 'Tutelle',
                'db_table': 'tutelle',
            },
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.FloatField()),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.devise')),
            ],
            options={
                'verbose_name': 'taux',
                'db_table': 'taux',
            },
        ),
        migrations.CreateModel(
            name='SituationFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.BigIntegerField()),
                ('arriere', models.BigIntegerField()),
                ('paye', models.BigIntegerField()),
                ('reference_lettre', models.CharField(max_length=200)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.devise')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation')),
            ],
            options={
                'verbose_name': ' Situation Financiere',
                'db_table': 'situation_financiere',
            },
        ),
        migrations.CreateModel(
            name='Proposition_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.planengagement')),
            ],
            options={
                'verbose_name': ' Proposition Plan',
                'db_table': 'proposition_plan',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='tutelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tutelle'),
        ),
        migrations.CreateModel(
            name='LigneGblobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.BigIntegerField()),
                ('montant_disponible', models.BigIntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
            ],
            options={
                'verbose_name': ' Situation Financiere',
                'db_table': 'ligne_globale',
            },
        ),
        migrations.AddField(
            model_name='exercice',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.statut'),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=400)),
                ('montant_engage', models.BigIntegerField()),
                ('montant_paye', models.BigIntegerField(null=True)),
                ('date_engagement', models.DateTimeField()),
                ('date_miseajour', models.DateTimeField(null=True)),
                ('referenceov', models.CharField(max_length=20, null=True)),
                ('bordereau_engagement', models.CharField(max_length=400)),
                ('bordereau_avis', models.CharField(max_length=400)),
                ('contribution_apaye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.situationfinanciere')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.devise')),
                ('etat_dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etatdossier')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation')),
                ('source_financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sourcefinancement')),
            ],
            options={
                'verbose_name': 'Engagement',
                'db_table': 'engagement',
            },
        ),
    ]
