# Generated by Django 4.2.1 on 2023-09-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devise',
            options={'verbose_name': 'Devise'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name': 'Engagement'},
        ),
        migrations.AlterModelOptions(
            name='proposition_plan',
            options={'verbose_name': ' Proposition Plan'},
        ),
        migrations.AlterModelOptions(
            name='taux',
            options={'verbose_name': 'taux'},
        ),
        migrations.AlterModelOptions(
            name='tutelle',
            options={'verbose_name': 'Tutelle'},
        ),
        migrations.AlterModelOptions(
            name='typetutelle',
            options={'verbose_name': 'Type Tutelle'},
        ),
        migrations.AlterModelTable(
            name='engagement',
            table='engagement',
        ),
        migrations.AlterModelTable(
            name='lignegblobale',
            table='ligne_globale',
        ),
        migrations.AlterModelTable(
            name='planengagement',
            table='plan_engagement',
        ),
        migrations.AlterModelTable(
            name='proposition_plan',
            table='proposition_plan',
        ),
        migrations.AlterModelTable(
            name='situationfinanciere',
            table='situation_financiere',
        ),
    ]
