# Generated by Django 4.2.1 on 2023-10-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('document', models.CharField(max_length=100)),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tutelle')),
                ('objet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation')),
            ],
            options={
                'verbose_name': 'Lettre',
                'db_table': 'lettre',
            },
        ),
    ]
