# Generated by Django 4.2.1 on 2023-10-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_lettre'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettre',
            name='exercice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice'),
        ),
    ]
