# Generated by Django 4.2.1 on 2023-10-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_lettre_exercice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lettre',
            old_name='objet',
            new_name='organisation',
        ),
    ]
