# Generated by Django 4.2.1 on 2023-10-08 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_objet_lettre_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignegblobale',
            name='montant_actuel',
            field=models.BigIntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lettre',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation'),
            preserve_default=False,
        ),
    ]
