# Generated by Django 4.2.1 on 2023-10-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_devise_options_alter_engagement_options_and_more'),
        ('gestion', '0004_rename_objet_lettre_organisation'),
    ]

    operations = [
    ]
