# Generated by Django 4.2.1 on 2023-10-08 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_lignegblobale_montant_actuel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignegblobale',
            old_name='montant_disponible',
            new_name='credit_actuel',
        ),
        migrations.RenameField(
            model_name='lignegblobale',
            old_name='montant_initial',
            new_name='credit_disponible',
        ),
        migrations.RemoveField(
            model_name='lignegblobale',
            name='montant_actuel',
        ),
        migrations.AddField(
            model_name='lignegblobale',
            name='credit_lfi',
            field=models.BigIntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignegblobale',
            name='credit_lfr',
            field=models.BigIntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lettre',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.organisation'),
            preserve_default=False,
        ),
    ]
