# Generated by Django 4.2.1 on 2023-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_merge_20231006_1357'),
        ('gestion', '0006_rename_montant_disponible_lignegblobale_credit_actuel_and_more'),
    ]

    operations = [
    ]
