# Generated by Django 4.2.1 on 2023-09-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='telephone',
        ),
    ]
