# Generated by Django 4.2.1 on 2023-09-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_users_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='users',
            name='service',
        ),
        migrations.RemoveField(
            model_name='users',
            name='titre',
        ),
    ]
