# Generated by Django 4.2.1 on 2023-09-23 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('flag_envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(null=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinateur', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'notification',
                'db_table': 'notification',
            },
        ),
    ]
