# Generated by Django 4.2.1 on 2023-09-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0003_remove_users_groupe_remove_users_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='users',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tutelle'),
        ),
        migrations.AddField(
            model_name='users',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='titre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.titre'),
        ),
    ]
