# Generated by Django 4.2.1 on 2023-09-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_users_groupe_users_service_users_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire_tutelle',
            options={'verbose_name': ' Comentraire tutelle'},
        ),
        migrations.AlterModelTable(
            name='commentaire_tutelle',
            table='commentaire_tutelle',
        ),
    ]
