# Generated by Django 4.2.1 on 2023-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_commentaire_tutelle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire_tutelle',
            name='date_val',
            field=models.DateTimeField(null=True),
        ),
    ]
