# Generated by Django 4.2.1 on 2023-09-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_notification'),
        ('login', '0006_alter_commentaire_tutelle_date_val'),
    ]

    operations = [
    ]
